# -*- coding: utf-8 -*-
"""Encryptix

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BH05_7bZ7qA0WXnHH1Pa9I1rycnTaPJX

   # IRIS flower classification
  from google.colab import files

  uploaded = files.upload()

  for fn in uploaded.keys():
    print('User uploaded file "{name}" with length {length} bytes'.format(
        name=fn, length=len(uploaded[fn])))
"""


import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv('IRIS.csv')
df.head()

# missing values
df.isnull().sum()
df.describe()

# class distribution
df['species'].value_counts()

X = df.drop(columns=['species'])
y = df['species']

# training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')
print(classification_report(y_test, y_pred))

new_data = [[5.1, 3.5, 1.4, 0.2]]

# prediction
prediction = model.predict(new_data)
predicted_species = prediction[0]
print(f'Predicted species: {predicted_species}')